use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    println!("cargo:rerun-if-env-changed=APP_EFFECTIVE_VERSION");
    println!("cargo:rerun-if-changed=web/dist");
    println!("cargo:rerun-if-changed=web/dist/assets");

    let effective_version =
        env::var("APP_EFFECTIVE_VERSION").unwrap_or_else(|_| env!("CARGO_PKG_VERSION").to_string());
    println!("cargo:rustc-env=PROXY_BROKER_BUILD_VERSION={effective_version}");

    if let Err(err) = generate_embedded_web_assets() {
        panic!("failed to generate embedded web assets: {err}");
    }
}

fn generate_embedded_web_assets() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let dist_dir = manifest_dir.join("web").join("dist");
    let index_html = dist_dir.join("index.html");
    let out_file = PathBuf::from(env::var("OUT_DIR")?).join("embedded_web_assets.rs");
    let profile = env::var("PROFILE").unwrap_or_default();

    if !index_html.is_file() {
        if profile == "release" {
            return Err(format!(
                "missing web/dist/index.html at {:?}; run `cd web && bun run build` before release builds",
                index_html
            )
            .into());
        }

        let placeholder = concat!(
            "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"/>",
            "<title>proxy-broker web ui not built</title></head><body>",
            "<main><h1>proxy-broker web ui not built</h1>",
            "<p>Run <code>cd web && bun run build</code> before starting the service in UI mode.</p>",
            "</main></body></html>"
        );
        let mut src = String::from("// @generated by build.rs; do not edit.\n");
        src.push_str("pub fn get(path: &str) -> Option<&'static [u8]> {\n");
        src.push_str("    match path {\n");
        src.push_str(&format!(
            "        \"index.html\" => Some({placeholder:?}.as_bytes()),\n"
        ));
        src.push_str("        _ => None,\n");
        src.push_str("    }\n");
        src.push_str("}\n");
        fs::write(out_file, src)?;
        return Ok(());
    }

    let mut files = Vec::new();
    collect_files_recursively(&dist_dir, &mut files)?;
    files.sort();

    let mut src = String::from("// @generated by build.rs; do not edit.\n");
    src.push_str("pub fn get(path: &str) -> Option<&'static [u8]> {\n");
    src.push_str("    match path {\n");
    for file in files {
        let rel = file
            .strip_prefix(&dist_dir)?
            .to_string_lossy()
            .replace('\\', "/");
        if rel.is_empty() {
            continue;
        }
        println!("cargo:rerun-if-changed=web/dist/{rel}");
        src.push_str(&format!(
            "        {rel:?} => Some(&include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), {suffix:?}))[..]),\n",
            suffix = format!("/web/dist/{rel}")
        ));
    }
    src.push_str("        _ => None,\n");
    src.push_str("    }\n");
    src.push_str("}\n");
    fs::write(out_file, src)?;
    Ok(())
}

fn collect_files_recursively(
    dir: &Path,
    out: &mut Vec<PathBuf>,
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let metadata = entry.metadata()?;
        if metadata.is_dir() {
            collect_files_recursively(&path, out)?;
        } else if metadata.is_file() {
            out.push(path);
        }
    }
    Ok(())
}
